import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HouseSVG from "@/components/HouseSVG";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from "@mui/material";
import theme from "./theme";
     {/* https://mui.com/material-ui/integrations/nextjs/?srsltid=AfmBOoq77c2MipSfoRwaJutX6aPQwOV6kbKSGjj-GZrqnO3pnrNViPSA */}
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className=" flex flex-row items-center w-full h-15 bg-gray-500">
          <a href="/" className="m-10">
            <HouseSVG />
          </a>
          <div>
            <h1 className="text-2xl">My Sign Ups</h1>
          </div>
        </div>
   
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
