
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Box, Container, Grid, Grid2, Link, ThemeProvider, Typography } from "@mui/material";
import theme from "./theme";
{/* https://mui.com/material-ui/integrations/nextjs/?srsltid=AfmBOoq77c2MipSfoRwaJutX6aPQwOV6kbKSGjj-GZrqnO3pnrNViPSA */ }
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import HomeIcon from '@mui/icons-material/Home';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Box sx={{ width:'100%',bgcolor: 'background.default' }}>

              <Grid2 container sx={{ bgcolor: 'secondary.main',paddingY:'.5rem' }} >
                <Grid2 size={.2}></Grid2>
                <Grid2 size={.6}>
                  <Link href="/">
                  <HomeIcon color="action" sx={{ fontSize: 40 }} />
                  </Link>
                </Grid2>
                <Grid2 size={4}>
                  <Typography color="secondary.dark" variant="h4">My Sign Ups</Typography>
                </Grid2>
              </Grid2>
              {children}
            </Box>
          </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
